# docker-compose.yml
version: '3'
services:
  api:
    build: ./src/api
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
