version: '3'

services:
  grafana:
    image: grafana/grafana:9.3.2
    container_name: mlops-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/notifiers:/etc/grafana/provisioning/notifiers
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
      - ../../grafana/dashboards:/etc/grafana/dashboards
      - ../../grafana/alerts:/etc/grafana/alerts
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - mlops-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: mlops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge
